[package]
name = "Red Wisdom"
description = "[PLACEHOLDER TEXT]"
homepage = "TBD"
authors = [
	"AFFA",
	"Greatness7",
	"Melchior Dahrk",
]
version = "1.0.0"

[dependencies]
assets = [ 
	"Red Wisdom.ESP",
]

[dependencies.mods."OAAB_Data"]
version = ">=2.3.1"
url = "https://www.nexusmods.com/morrowind/mods/49042"

[dependencies.mods."Tamriel_Data"]
plugin = "Tamriel_Data.esm"
url = "https://www.nexusmods.com/morrowind/mods/44537"